app/urls.py
from app.views import *

from django.urls import path

app_name='india'

urlpatterns=[

    path('sai/',sai,name='sai')
]

app1/urls.py
from app1.views import *

from django.urls import path

app_name='bharath'

urlpatterns=[

    path('babu/',babu,name='babu')
]

app2/urls.py
from app2.views import*
from django.urls import path
app_name='sindhu'

urlpatterns=[

path('chay/',chay,name='chay')
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def sai(request):
    return render(request,'one.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def babu(request):
    return render(request,'two.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def chay(request):
    return render(request,'three.html')

templates/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi helloooo.....</h1>
       <h1> <a href="{% url 'bharath:babu' %}">click</a></h1>
      
    </center>
</body>
</html>

templates/three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>thi is sai.....</h1>
    <h1> <a href="{% url 'india:sai' %}">go through</a></h1>
   
</body>
</html>

templates/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi how r u????????</h1>
        <h1> <a href="{% url 'sindhu:chay' %}">press</a></h1>
        
    </center>
</body>
</html>